### PR TITLE
Added CSV export option

### PR DESCRIPTION
**Pull request by aaronweaver**
Ability to export the results to a csv file.

### CODE REVIEW

**Comment by riramar** [comment]
Hi @aaronweaver,

Thanks for the PR. I'll take a look on that as soon as I have some time and let you know.

**Comment by riramar** [comment]
Hi @aaronweaver,

Sorry for the delay.
I didn't get the idea of the "Severity" column. From my tests all "RESPONSE HEADERS" will always be "Info" and all "RESPONSE MISSING HEADERS" will always be "Low".
Could you please give more details about the "Severity"?

Thanks!
Ricardo Iramar

**Comment by aaronweaver** [comment]
Hi @riramar - My main reason for writing the CSV exporter is so that I can integrate it in DefectDojo (https://github.com/DefectDojo/django-DefectDojo). For that any "finding" needs a severity and when I import it that makes it much easier. If that doesn't work for you I can re-submit without it and just decide it on the fly when I import.

Thanks!

**Comment by riramar** [comment]
@aaronweaver got it! Please remove and re-submit it so I can reevaluate your PR. Thanks!

**Comment by riramar** [comment]
@aaronweaver did some changes so if you want you can send the PR on the new code. Thanks!

**Pull request closed without merging**
